-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Isplata"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ZaposlenikID" integer NOT NULL,
    "Datum" timestamp without time zone NOT NULL,
    "Plaća" integer NOT NULL,
    CONSTRAINT "Isplata_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Plaća"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Netto" double precision NOT NULL,
    "Brutto" double precision NOT NULL,
    "Zdravstveno" double precision NOT NULL,
    "Mirovinsko" double precision NOT NULL,
    "Putni trošak" double precision,
    "Total" double precision NOT NULL,
    CONSTRAINT "Plaća_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Radno mjesto"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Radno mjesto" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Radno mjesto_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Status"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Status_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Trošak"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Opis" text COLLATE pg_catalog."default",
    "Iznos" double precision NOT NULL,
    "Datum" date NOT NULL,
    "Vrsta" integer NOT NULL,
    CONSTRAINT "Trošak_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Trošak_Vrsta"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Naziv" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Trošak_Vrsta_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Vozilo"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Marka" text COLLATE pg_catalog."default" NOT NULL,
    "Reg. tablice" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Vrijeme zadnjeg servisa" date NOT NULL,
    "Vrijeme idućeg servisa" date NOT NULL,
    "Vrijeme zadnje registracije" date NOT NULL,
    "Istek registracije" date NOT NULL,
    "Potrošnja" double precision NOT NULL,
    "Kilometraža" integer NOT NULL,
    "Zapremina rezervara" integer NOT NULL,
    CONSTRAINT "Vozilo_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."WorkLog"
(
    "ZaposlenikID" integer NOT NULL,
    "Datum" date NOT NULL,
    "Status" integer NOT NULL,
    "Vozilo" integer,
    "Kilometraža" integer,
    "Dnevnik" text COLLATE pg_catalog."default",
    "Trošak" integer,
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "WorkLog_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Zaposlenik"
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Ime i prezime" text COLLATE pg_catalog."default" NOT NULL,
    "Kontakt" text COLLATE pg_catalog."default" NOT NULL,
    "Plaća" integer NOT NULL,
    "Lozinka" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "Radno vrijeme pocetak" time without time zone NOT NULL,
    "Radno vrijeme kraj" time without time zone NOT NULL,
    "Vozilo" integer,
    "Radno mjesto" integer NOT NULL,
    "Zaposlen" date NOT NULL,
    CONSTRAINT "Zaposlenik_pkey" PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Isplata"
    ADD CONSTRAINT "Plaća" FOREIGN KEY ("Plaća")
    REFERENCES public."Plaća" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Isplata"
    ADD CONSTRAINT "ZaposlenikID" FOREIGN KEY ("ZaposlenikID")
    REFERENCES public."Zaposlenik" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Trošak"
    ADD CONSTRAINT "Vrsta" FOREIGN KEY ("Vrsta")
    REFERENCES public."Trošak_Vrsta" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."WorkLog"
    ADD CONSTRAINT "StatusiD" FOREIGN KEY ("Status")
    REFERENCES public."Status" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."WorkLog"
    ADD CONSTRAINT "TrošakID" FOREIGN KEY ("Trošak")
    REFERENCES public."Trošak" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."WorkLog"
    ADD CONSTRAINT "VoziloID" FOREIGN KEY ("Vozilo")
    REFERENCES public."Vozilo" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zaposlenik"
    ADD CONSTRAINT "Plaća" FOREIGN KEY ("Plaća")
    REFERENCES public."Plaća" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zaposlenik"
    ADD CONSTRAINT "Radno mjesto" FOREIGN KEY ("Radno mjesto")
    REFERENCES public."Radno mjesto" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Zaposlenik"
    ADD CONSTRAINT "Vozilo iD" FOREIGN KEY ("Vozilo")
    REFERENCES public."Vozilo" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;